# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loglint < Formula
  desc "Linter by analyzing build log."
  homepage "https://github.com/mattak/unityguid"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mattak/loglint/releases/download/v1.0.0/loglint_darwin_x86_64.tar.gz"
      sha256 "a80fd816fefeb27c244e5d37a340658d5bacb971863c3490c1b039f345764f35"

      def install
        bin.install "loglint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mattak/loglint/releases/download/v1.0.0/loglint_darwin_arm64.tar.gz"
      sha256 "4dd8dc986b3e78c11c446d4d4141febd22aa9c8f62d27ffb00307ffe2d7a4a6c"

      def install
        bin.install "loglint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattak/loglint/releases/download/v1.0.0/loglint_linux_arm64.tar.gz"
      sha256 "643364f4667fb5fac3f512530fedbde0ef07227949df872eb3c337930ced600f"

      def install
        bin.install "loglint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mattak/loglint/releases/download/v1.0.0/loglint_linux_x86_64.tar.gz"
      sha256 "4f6aed258e0e7b3d0f1400c6416d9a110ebe84fa56fcf1b3174aee809502d0da"

      def install
        bin.install "loglint"
      end
    end
  end
end
