# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loglint < Formula
  desc "Linter by analyzing build log."
  homepage "https://github.com/mattak/unityguid"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mattak/loglint/releases/download/v1.0.1/loglint_darwin_arm64.tar.gz"
      sha256 "548aeab4776af16a0f25e7b92982725ca3dbe63a75ad6fab44da67da5bfeff55"

      def install
        bin.install "loglint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mattak/loglint/releases/download/v1.0.1/loglint_darwin_x86_64.tar.gz"
      sha256 "9d87bec42f4cda1ecf09ce5c594e694b0353a421c86e16d6b17b4d7bcd008840"

      def install
        bin.install "loglint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattak/loglint/releases/download/v1.0.1/loglint_linux_arm64.tar.gz"
      sha256 "836d8a06f910ceab6c942159325fb37320d46550bcb334ece79ae611ca4ba39a"

      def install
        bin.install "loglint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mattak/loglint/releases/download/v1.0.1/loglint_linux_x86_64.tar.gz"
      sha256 "67a6f991513060713b18c7c8cbb5476b6ab6f9f489dca4baac0bd604a99eba65"

      def install
        bin.install "loglint"
      end
    end
  end
end
